### ISSUE TITLE
Add TZ to README

### ISSUE THREAD

**Issue by m4r1k** [activecs/docker-cron-restart-notifier#66]
The TZ variable is supported and allows for correctly setting the relevant timezone.
```
    restart-notifier:
      container_name: restart-notifier
      image: deduard/tools:restart-notifier-20250417
      restart: unless-stopped
      environment:
        RESTART_CONTAINERS: "foo,bar"
        RUN_ON_STARTUP: "false"
        CRON_SCHEDULE: "0 4 * * *" # Every 4:00am
        CYCLE_PERIOD: "10000" # 10 sec
        TZ: "Europe/Amsterdam"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
```

Please consider adding it to the README

**Comment by nichols89ben** [comment]
I second this, it took me a long time to figure out why it wasn’t triggering on the cron. However, even when adding the TZ and /etc/localtime path, it still refused to update past UTC. The only thing I could do was convert my time to UTC to trigger it when I wanted. 


   ```
environment:
      TZ: America/New_York
      CRON_SCHEDULE: "0 8 * * *"   # During daylight saving 4 AM EST → 08:00 UTC
      #CRON_SCHEDULE: "0 9 * * *"   # During standard time 4 AM EDT → 09:00 UTC
    volumes:
      - /etc/localtime:/etc/localtime:ro
```

**Comment by babsonnexus** [comment]
> The only thing I could do was convert my time to UTC to trigger it when I wanted.

@nichols89ben, thanks for the info. I was thinking this didn't actually work until I converted to UTC as it completely ignores TZ.

@activecs, I also put together a Portainer Stack that uses environment variables instead of hardcoding:

```
services:
  restart-notifier:
    image: index.docker.io/deduard/tools:restart-notifier-latest
    container_name: restart-notifier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
#      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}    # i.e., https://discord.com/api/webhooks/119207436456853270/mRC3HfPoT5_MFsvn3sHUuG1Qeeg3WTUAo_bf0LR8
#      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}        # i.e., https://hooks.slack.com/services/T04JS2CSY4U/B06HRRFSRGW/1UL9bv1i1JnaYsUBo
      - RESTART_CONTAINERS=${RESTART_CONTAINERS}       # i.e., nervous_moore1,nervous_moore2
      - RUN_ON_STARTUP=${RUN_ON_STARTUP}               # i.e., false
      - CRON_SCHEDULE=${CRON_SCHEDULE}                 # i.e., 0 4 * * FRI     # INFO: This would be every Friday at 4:00 AM, but must be UTC
      - CYCLE_PERIOD=${CYCLE_PERIOD}                   # i.e., 10000           # INFO: This would be 10 seconds
#      - TZ=${TIMEZONE:-UTC}
    restart: unless-stopped
```

As you can see, I included the `TZ` in the hope of future functionality, but commented out.

![Image](https://github.com/user-attachments/assets/bb0befc6-b462-4655-88a7-9b4180f762f1)
